{% set name = "caterva" %}
{% set version = "2024.07.01" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Blosc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e71b9c413b49921f705b6c68ea7a2649407957cec795d34cb887c0135c187b13
  patches:
    # Patches that must be consolidated in upstream
    - caterva.patch


build:
  number: 0
  run_exports:
    - {{ pin_subpackage('caterva') }}
  # TODO: Remove once there is a stable 2.x release of c-blosc2
  ignore_run_exports:
    - c-blosc2

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - c-blosc2
  run:
    - c-blosc2

test:
  commands:
    - test -e $PREFIX/include/{{ name }}.h                   # [unix]
    - test -e $PREFIX/lib/lib{{ name }}${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\{{ name }}.h exit 1         # [win]
    - if not exist %LIBRARY_BIN%\{{ name }}.dll exit 1       # [win]
    - if not exist %LIBRARY_LIB%\lib{{ name }}.lib exit 1    # [win]

about:
  home: https://github.com/Blosc/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A multidimensional data container on top of Blosc2'

  description: |
    Caterva is a C library for handling multi-dimensional, compressed datasets in an easy and convenient manner. It implements a thin metalayer on top of C-Blosc2 for specifying not only the dimensionality of a dataset, but also the dimensionality of the chunks inside the dataset. In addition, Caterva adds machinery for retrieving arbitrary multi-dimensional slices (aka hyper-slices) out of the multi-dimensional containers in the most efficient way. Hence, Caterva brings the convenience of multi-dimensional and compressed containers to your application very easily.

extra:
  recipe-maintainers:
    - FrancescAlted
    - aleix11alcacer
